### ISSUE TITLE
Fix vulnerability CVE-2022-46337

### ISSUE THREAD

**Issue by sanchayata-jain-cko** [flyway/flyway-docker#131]
Docker image is affected by a Fixable https://github.com/advisories/GHSA-rcjc-c4pj-xxrp in library 'org.apache.derby:derby' (version 10.16.1.1), resolved by version 10.17.1.0

**Comment by jmcruz1983** [comment]
Any update here?

**Comment by Barry-RG** [comment]
Please see the [release notes](https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine) for Flyway 10.7.1 and details added to the Derby [support page](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/derby).
Unfortunately since Flyway cannot currently upgrade to support Java 21 and Derby have not released a fix for their versions which support Java 17, we have had to remove the Derby driver and leave it to the user to make their decision on how to approach this.
