### ISSUE TITLE
Allow drivers from multiple locations.

### ISSUE THREAD

**Issue by pradeepvishwakarma** [flyway/flyway-docker#32]
Using docker image [flyway/flyway], I'm unable to add [ADAL drivers](https://flywaydb.org/documentation/database/sqlserver#azure-active-directory) to flyway container.

Could you please advise how can we add addtional drivers on top of existing ones.

OR

We should add advantage of nested driver lookup :  ${DATA_ROOT}/drivers/adal:/flyway/drivers/adal

**Comment by DoodleBobBuffPants** [comment]
This is due to how docker works. Mounting volumes will override the existing contents in the target location. There are two solutions you could try:

- If you aren't using the `/flyway/jars` location you could try to add those drivers to `/flyway/jars` as they will also be loaded from there
- You can include the database drivers you need in your local directory before mapping volumes. You can find the driver you need [here](https://flywaydb.org/documentation/database/sqlserver#driver)

**Comment by pradeepvishwakarma** [comment]
@DoodleBobBuffPants Thanks for your advise. I'll try second option because it looks more cleaner.
